<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Base extends Controller
{
    /**
     * 初始化父类操作
     */
    protected function _initialize()
    {
        // 继承父类中的初始化操作
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


}
